version: '3'
services:
    view:
        build:
            context: ./
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.view.rule=Host(`drewjocham.com`)"
            #- "traefik.http.routers.view.entrypoints=websecure"
            - "traefik.http.routers.view.tls=true"
            - "traefik.http.routers.view.tls.certresolver=myresolver"
        networks:
            - traefik
        ports:
            - "8080"
    reverse-proxy:
        image: traefik:v2.11
        command: --configFile=/etc/traefik/traefik.yml
        ports:
            - "80:443"
            #- "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/etc/traefik/traefik.yml
            - ./acme.json:/acme.json
        networks:
            - traefik
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
        restart: unless-stopped
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prom_data:/prometheus
volumes:
    grafana-storage: {}
    prom_data:

networks:
    traefik:
        external: true
