version: '3.0'
services:
    view:
        build:
            context: ./
        environment:
            - API_HOST=api
            - API_PORT=8081
            - PORT=8080 # port is a reserved env name on GCP
            - NODE_ENV=production
        networks:
            - personal
        ports:
            - "80:8080"
            - "443:443"
networks:
    personal:
