entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        exposedByDefault: false

certificatesResolvers:
    myresolver:
        acme:
            email: drew@jocham.io
            storage: acme.json
            httpChallenge:
                entryPoint: web

http:
    routers:
        http-catchall:
            rule: "HostRegexp(`{host:.+}`)"
            entryPoints:
                - web
            middlewares:
                - redirect-to-https

    middlewares:
        redirect-to-https:
            redirectScheme:
                scheme: https
                permanent: true
        hsts:
            headers:
                -   name: Strict-Transport-Security
                    value: "max-age=31536000; includeSubDomains; preload"

